name: 'Apple Code Signing Setup'
description: 'Sets up Apple code signing certificates and provisioning profiles using fastlane match'
author: 'Your Name'

branding:
  icon: 'lock'
  color: 'gray-dark'

inputs:
  use_session:
    description: 'Use Apple ID session authentication instead of App Store Connect API'
    required: false
    default: 'false'
  generate_macos:
    description: 'Generate macOS certificates and profiles'
    required: false
    default: 'false'
  generate_ios:
    description: 'Generate iOS certificates and profiles'
    required: false
    default: 'false'
  generate_appstore:
    description: 'Generate App Store certificates (macOS only)'
    required: false
    default: 'false'
  generate_developer_id:
    description: 'Generate Developer ID certificates (macOS only)'
    required: false
    default: 'false'
  generate_pkg:
    description: 'Generate PKG installer certificates (macOS only)'
    required: false
    default: 'false'

  # Required secrets (passed as inputs in composite actions)
  gh_pat:
    description: 'GitHub Personal Access Token for accessing match repository'
    required: true
  match_repository:
    description: 'Git repository for storing certificates (format: org/repo)'
    required: true
  match_password:
    description: 'Password to encrypt/decrypt certificates'
    required: true
  match_deploy_key:
    description: 'SSH deploy key for match repository (optional - will be generated if not provided)'
    required: false
    default: ''

  # Apple credentials (required based on use_session)
  fastlane_user:
    description: 'Apple ID email (required if use_session is true)'
    required: false
    default: ''
  fastlane_password:
    description: 'Apple ID password (required if use_session is true)'
    required: false
    default: ''
  fastlane_session:
    description: 'Fastlane session cookie (required if use_session is true)'
    required: false
    default: ''

  # App Store Connect API (required if use_session is false)
  appstore_issuer_id:
    description: 'App Store Connect API issuer ID (required if use_session is false)'
    required: false
    default: ''
  appstore_key_id:
    description: 'App Store Connect API key ID (required if use_session is false)'
    required: false
    default: ''
  appstore_p8:
    description: 'App Store Connect API private key content (required if use_session is false)'
    required: false
    default: ''

  # Bundle IDs
  mac_bundle_id:
    description: 'macOS application bundle identifier (required if generate_macos is true)'
    required: false
    default: ''
  ios_bundle_id:
    description: 'iOS application bundle identifier (required if generate_ios is true)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        working-directory: ${{ github.action_path }}

    - name: Fastlane Init and Sync Certificates
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        # Setup SSH for match repository
        eval "$(ssh-agent -s)"

        if [[ -n "$MATCH_DEPLOY_KEY" ]]; then
          # Use provided deploy key
          echo "Using provided MATCH_DEPLOY_KEY"
          ssh-add - <<< "$MATCH_DEPLOY_KEY"
        else
          # Generate deploy key using fastlane plugin
          echo "Generating deploy key with fastlane init_ci"
          bundle exec fastlane ios init_ci
          ssh-add - <<< "$(cat MATCH_DEPLOY_KEY)"
        fi

        # Sync certificates
        [[ $GENERATE_IOS == true ]] && bundle exec fastlane ios sync_certificates
        [[ $GENERATE_MACOS == true ]] && bundle exec fastlane mac sync_certificates
        echo "Finished!"
      env:
        FASTLANE_USER: ${{ inputs.fastlane_user }}
        FASTLANE_PASSWORD: ${{ inputs.fastlane_password }}
        FASTLANE_SESSION: ${{ inputs.fastlane_session }}
        APPSTORE_ISSUER_ID: ${{ inputs.appstore_issuer_id }}
        APPSTORE_KEY_ID: ${{ inputs.appstore_key_id }}
        APPSTORE_P8: ${{ inputs.appstore_p8 }}
        MAC_BUNDLE_ID: ${{ inputs.mac_bundle_id }}
        IOS_BUNDLE_ID: ${{ inputs.ios_bundle_id }}
        GH_PAT: ${{ inputs.gh_pat }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        MATCH_REPOSITORY: ${{ inputs.match_repository }}
        MATCH_PASSWORD: ${{ inputs.match_password }}
        MATCH_DEPLOY_KEY: ${{ inputs.match_deploy_key }}
        GENERATE_DEVELOPER_ID: ${{ inputs.generate_developer_id }}
        GENERATE_APPSTORE: ${{ inputs.generate_appstore }}
        GENERATE_IOS: ${{ inputs.generate_ios }}
        GENERATE_MACOS: ${{ inputs.generate_macos }}
        GENERATE_PKG: ${{ inputs.generate_pkg }}
        USE_SESSION: ${{ inputs.use_session }}
